### ISSUE TITLE
Instalation problems

### ISSUE THREAD

**Issue by fjborquez** [MartinKondor/DjangoUserSys#1]
Hey!, I tried to install but there are problems with these dependencies when starting the server: 

- bootstrap5
- crispy_forms
- crispy_bootstrap5
- psycopg2

I'm using PyCharm and venv.
Idk if the solution is adding these dependencies to requirements.txt

**Comment by MartinKondor** [comment]
Hey! Yes, the requirements file is incorrect.

Here is the correct requirements.txt:
```
Django==4.2.11
psycopg==3.1.18
django-bootstrap-v5==1.0.11
django-crispy-forms==2.1
crispy-bootstrap5==2024.2
```
Feel free to make a pull request with it!:)
But first, make sure to `git pull`.

**Comment by fjborquez** [comment]
did you already added it?

**Comment by MartinKondor** [comment]
Yes, sorry!

**Comment by fjborquez** [comment]
no problem! 😄
