### ISSUE TITLE
Default admin user

### ISSUE THREAD

**Issue by fjborquez** [MartinKondor/DjangoUserSys#3]
Hey!, I installed the migrations but there is no admin user.
Is there any missing configuration or I am doing something wrong?

**Comment by MartinKondor** [comment]
Hey! No, I didn't set a default admin user yet, but feel free to contribute if you'd like!:D

**Comment by fjborquez** [comment]
ok, give me some time because I have to work 😅

**Comment by fjborquez** [comment]
python manage.py createsuperuser did the trick 😅
